TiendaDeportiva/ViewModels/DetailsViewModel.cs
using TiendaDeportiva.Models;

namespace TiendaDeportiva.ViewModels
{
    public class DetailsViewModel
    {
        public Product product { get; set; }
        public string NombreCliente { get; set; }
    }
}

TiendaDeportiva/ViewModels/ListProductViewModel.cs
using System.Collections.Generic;
using TiendaDeportiva.Models;

namespace TiendaDeportiva.ViewModels
{
    public class ListProductViewModel
    {
        public List<Product> Products { get; set; }

        public ListProductViewModel()
        {
            Products = new List<Product>();
        }

    }
}

TiendaDeportiva/ViewModels/ListUsersViewModel.cs
using System.Collections.Generic;
using TiendaDeportiva.Models;

namespace TiendaDeportiva.ViewModels
{
    public class ListUsersViewModel
    {
        public List<UsuarioModel> Users { get; set; }

        public ListUsersViewModel()
        {
            Users = new List<UsuarioModel>();
        }

    }
}

TiendaDeportiva/Controllers/StoreController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TiendaDeportiva.Models;
using TiendaDeportiva.Services;
using TiendaDeportiva.ViewModels;

namespace TiendaDeportiva.Controllers
{
    //https://localhost:5001/Store
    [Route("[controller]")]
    public class StoreController : Controller
    {

        #region Properties
        private readonly TiendaDeportivaDBContext dBContext;
        #endregion

        #region Constructor
        public StoreController(TiendaDeportivaDBContext dBContext)
        {
            this.dBContext = dBContext;
        }

        #endregion Constructor

        //https://localhost:5001/Store/TestStore
        [HttpGet("TestStore")]
        public string TestStore()
        {
            return "Mi primer metodo";
        }

        //https://localhost:5001/Store/SayHello/name
        [HttpGet("SayHello/{name}")]
        public string SayHello(string name)
        {
            return "Hola Sr/Sra. " + name;
        }

        //https://localhost:5001/Store/TestPost/
        [HttpPost("TestPost")]
        public string TestPost([FromBody]Product product)
        {
            return product.Nombre;
        }

        //https://localhost:5001/Store/ActionPost/
        [HttpPost("ActionPost")]
        public IActionResult ActionPost([FromBody]Product product)
        {
            return Ok(product);
        }

        //https://localhost:5001/Store/InfoProduct/
        [HttpGet("InfoProduct/{nombre}/{apellido}")]
        public IActionResult InfoProduct(string nombre, string apellido)
        {
            ViewData["nombre"] = nombre;
            ViewData["apellido"] = apellido;
            return View();
        }

        //https://localhost:5001/Store/Details/nombreCliente
        [HttpGet("Details/{nombreCliente}")]
        public IActionResult Details(string nombreCliente)
        {
            DetailsViewModel DetailsView = new DetailsViewModel();
            Product product = new Product()
            {
                Nombre = "Raqueta",
                Precio = 320000,
                Color = "Blanca"
            };
            DetailsView.product = product;
            DetailsView.NombreCliente = nombreCliente;
            return View(DetailsView);
        }

        //https://localhost:5001/Store/ListProducts
        [HttpGet("ListProducts")]
        public IActionResult ListProducts()
        {
            ListProductViewModel ListProductsView = new ListProductViewModel();
            Product product1 = new Product()
            {
                Nombre = "Raqueta",
                Precio = 320000,
                Color = "Blanca"
            };
            Product product2 = new Product()
            {
                Nombre = "Balon Futbol",
                Precio = 100000,
                Color = "W/B"
            };
            Product product3 = new Product()
            {
                Nombre = "Tennis",
                Precio = 200000,
                Color = "Azules"
            };
            ListProductsView.Products.Add(product1);
            ListProductsView.Products.Add(product2);
            ListProductsView.Products.Add(product3);
            return View(ListProductsView);
        }

        //https://localhost:5001/Store/CreateProduct
        [HttpGet("CreateProduct")]
        public IActionResult CreateProduct()
        {
            return View();
        }

        //https://localhost:5001/Store/SaveProduct/
        [HttpPost("SaveProduct")]
        public IActionResult SaveProduct(Product product)
        {
            return Ok(product.Color);
        }

        //https://localhost:5001/Store/CreateUser
        [HttpGet("CreateUser")]
        public async Task<IActionResult> CreateUser()
        {
            UsuarioModel Usuario = new UsuarioModel()
            {
                Nombre = "Pepito",
                Apellido = "Perez",
                Edad = 54
            };
            dBContext.usuariosla.Add(Usuario);
            await dBContext.SaveChangesAsync();

            return Ok(Usuario.Id.ToString());
        }

        //https://localhost:5001/Store/ListUsers
        [HttpGet("ListUsers")]
        public async Task<IActionResult> ListUsersAsync()
        {
            ListUsersViewModel vm = new ListUsersViewModel();
            vm.Users = await dBContext.usuariosla.ToListAsync();
            // vm.Users = vm.Users.Where(u => u.Nombre == "Gustavo").ToList();
            return View(vm);
        }

        //https://localhost:5001/Store/DeleteUser/1
        [HttpGet("DeleteUser/{id}")]
        public async Task<IActionResult> DeleteUser(long id)
        {
            try
            {
                UsuarioModel usuario = await dBContext.usuariosla.FindAsync(id);
                if (usuario == null)
                    throw new Exception("Usuario no encontrado");

                dBContext.usuariosla.Remove(usuario);
                await dBContext.SaveChangesAsync();
                return Ok("Usuario Borrado");
            }
            catch (Exception e)
            {
                return Content(e.Message);
            }
        }

        //https://localhost:5001/Store/EditUser/1
        [HttpGet("EditUser/{id}")]
        public async Task<IActionResult> EditUser(long id)
        {
            try
            {
                UsuarioModel usuario = await dBContext.usuariosla.FindAsync(id);
                if (usuario == null)
                    throw new Exception("El usuario no existe");
                return View(usuario);
            }
            catch(Exception e)
            {
                return Content(e.Message);
            }
        }

        //https://localhost:5001/Store/UpdateUser
        [HttpPost("UpdateUser")]
        public async Task<IActionResult> UpdateUser(UsuarioModel Usuario)
        {
            try
            {
                dBContext.Entry(Usuario).State = EntityState.Modified;
                await dBContext.SaveChangesAsync();
                return Redirect("/Store/ListUsers");
            }
            catch (Exception e)
            {
                return Content(e.Message);
            }
        }

        //https://localhost:5001/Store/Index
        [HttpGet("Index")]
        public IActionResult Index()
        {
            return View();
        }

    }
}

TiendaDeportiva/Views/Store/CreateProduct.cshtml
@model TiendaDeportiva.Models.Product

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        <form asp-action="SaveProduct" method="POST">
            <div>
                <label asp-for="Nombre"></label>
                <input asp-for="Nombre"/>
            </div>

            <div>
                <label asp-for="Precio"></label>
                <input asp-for="Precio"/>
            </div>

            <div>
                <label asp-for="Color"></label>
                <input asp-for="Color"/>
            </div>

            <div>
                <input type="submit" value="Guardar Producto">
            </div>
        </form>
    </div>
</body>
</html>

TiendaDeportiva/Views/Store/Details.cshtml
@model TiendaDeportiva.ViewModels.DetailsViewModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        <h1>@Model.NombreCliente</h1>
        @* <h1>@Html.DisplayFor(model => model.product.Nombre)</h1> *@
        <label for="">Precio : @Html.DisplayFor(model => model.product.Precio)</label>
        <label for="">Color : @Html.DisplayFor(model => model.product.Color)</label>

        <label for="">Gracias por visitarnos señor 
            @Html.DisplayFor(model => model.NombreCliente)</label>
    </div>
</body>
</html>

TiendaDeportiva/Views/Store/EditUser.cshtml
@model TiendaDeportiva.Models.UsuarioModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/EditUserStyle.css">
    <title>Document</title>
</head>
<body>
    <div id="WrapperScreen">
        @* <a asp-controller="Store" asp-action="ListUsersAsync">Volver</a> *@
        <form asp-action="UpdateUser" method="POST">
            <input type="hidden" asp-for="Id">
            <div>
                <label class="InfoFormulario" asp-for="Nombre"></label>
                <input asp-for="Nombre"/>
            </div>

            <div>
                <label class="InfoFormulario" asp-for="Apellido"></label>
                <input asp-for="Apellido"/>
            </div>

            <div>
                <label class="InfoFormulario" asp-for="Edad"></label>
                <input asp-for="Edad"/>
            </div>

            <div>
                <input type="submit" value="Guardar Producto">
            </div>
        </form>
    </div>
</body>
</html>

TiendaDeportiva/Views/Store/InfoProduct.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        *.{
            margin: 0:
            padding: 0:
        }

        body{
            background-color: aliceblue;
        }

        label{
            color: black;
            font-size: 1.3em;
        }
    </style>
</head>
<body>
    <h1>MI PRIMERA SEGUNDO</h1>
    <label for="">@ViewData["nombre"]</label>
    <label for="">@ViewData["apellido"]</label>
</body>
</html>

TiendaDeportiva/Views/Store/ListProducts.cshtml
@model TiendaDeportiva.ViewModels.ListProductViewModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ul>
        @foreach (var item in Model.Products)
        {
            <li>Nombre Producto : @Html.DisplayFor(modelItem => item.Nombre)</li>
            <li>Precio: @Html.DisplayFor(modelItem => item.Precio)</li>
            <li>Color: @Html.DisplayFor(modelItem => item.Color)</li>
        }
    </ul>
</body>
</html>

TiendaDeportiva/Views/Store/ListUsers.cshtml
@model TiendaDeportiva.ViewModels.ListUsersViewModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ul>
        @foreach (var item in Model.Users)
        {
            <li>
                <label>Nombre : @Html.DisplayFor(modelItem => item.Nombre)</label>
                <label>Apellido: @Html.DisplayFor(modelItem => item.Apellido)</label>
                <label>Edad: @Html.DisplayFor(modelItem => item.Edad)</label>
                <a asp-controller="Store" asp-action="EditUser" asp-route-id="@item.Id">Editar</a>        
            </li>            
        }
    </ul>
</body>
</html>