Libreria/Models/AutorModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Libreria.Models
{
    public class AutorModel
    {
        [Key]
        public long Id { get; set; }
        public string Nombre { get; set; }
        public DateTime FechaNacimiento { get; set; }
        public int CantidadLibros { get; set; }
    }
}

Libreria/Models/ErrorViewModel.cs
using System;

namespace Libreria.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Libreria/Models/LibroModel.cs
using System.ComponentModel.DataAnnotations;

namespace Libreria.Models
{
    public class LibroModel
    {
        [Key]
        public long Id { get; set; }
        public string Nombre { get; set; }
        public int CantidadPaginas { get; set; }
        public string Genero  { get; set; }
        public long IdAutor { get; set; }
    }
}

Libreria/ViewModels/AutorBuscadorViewModel.cs
using System.Collections.Generic;
using Libreria.Models;

namespace Libreria.ViewModels
{
    public class AutorBuscadorViewModel
    {
        public AutorModel AutorBusqueda { get; set; }
        public bool HayUsuario { get; set; }

        public AutorBuscadorViewModel()
        {
            HayUsuario = false;
        }
    }
}

Libreria/ViewModels/LibrosIndexViewModel.cs
using System.Collections.Generic;
using Libreria.Models;

namespace Libreria.ViewModels
{
    public class LibrosIndexViewModel
    {
        public List<LibroModel> Libros { get; set; }
        public bool HayLibros { get; set; }

        public LibrosIndexViewModel()
        {
            Libros = new List<LibroModel>();
            HayLibros = true;
        }
    }
}

Libreria/Controllers/AutorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Libreria.Models;
using Libreria.Services;
using Libreria.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Libreria.Controllers
{
    [Route("[controller]")]
    public class AutorController : Controller
    {
        #region Properties
        private readonly LibreriaDBContext dBContext;
        #endregion

        #region Constructor
        public AutorController(LibreriaDBContext dBContext)
        {
            this.dBContext = dBContext;
        }
        #endregion

        [HttpGet("BuscadorAutores")]
        public IActionResult Buscador(AutorModel? autor)
        {
            AutorBuscadorViewModel vm = new AutorBuscadorViewModel();
            if (autor.Nombre != null)
                vm.HayUsuario = true;
            vm.AutorBusqueda = autor ?? new AutorModel();
            return View(vm);
        }

        public async Task<IActionResult> BuscarAutor(AutorBuscadorViewModel autorVm)
        {
            AutorModel Autor = new AutorModel();
            try
            {
                List<AutorModel> autores = await dBContext.Autores.ToListAsync();
                Autor = autores.First(a => a.Nombre == autorVm.AutorBusqueda.Nombre);
                return RedirectToAction("Buscador", "Autor", Autor);
            }
            catch(InvalidOperationException)
            {
                return RedirectToAction("Buscador", "Autor", null);
            }
        }
    }
}

Libreria/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;


namespace Libreria.Controllers
{
    public class HomeController : Controller
    {
        
        public IActionResult Index()
        {
            
            return View();
        }
    }
}

Libreria/Controllers/LibrosController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Libreria.Models;
using Libreria.Services;
using Libreria.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;

namespace Libreria.Controllers
{
    [Route("[controller]")]
    public class LibrosController : Controller
    {
        #region Properties
        private readonly LibreriaDBContext dBContext;
        private IMemoryCache _cache;
        #endregion

        #region Constructor
        public LibrosController(LibreriaDBContext dBContext, IMemoryCache memoryCache)
        {
            this.dBContext = dBContext;
            _cache = memoryCache;
        }
        #endregion
        


        //https://localhost:5001/Libros/ListaLibros
        [HttpGet("ListaLibros")]
        public async Task<IActionResult> Index()
        {
            

            var cacheEntryOptions = new MemoryCacheEntryOptions()
            // Keep in cache for this time, reset time if accessed.
            .SetSlidingExpiration(TimeSpan.FromMinutes(10));
            _cache.Set("test", "Holi", cacheEntryOptions);

            string cacheEntry = "";
            if (_cache.TryGetValue("test", out cacheEntry))
            {
                Console.WriteLine(cacheEntry);
            }

            LibrosIndexViewModel vm = new LibrosIndexViewModel();
            try
            {
                vm.Libros = await dBContext.Libros.ToListAsync();
                if (vm.Libros.Count <= 3)
                    throw new Exception("No hay libros");
                return View(vm);
            }
            catch (Exception e)
            {
                vm.HayLibros = false;
                return View(vm);
            }
        }
    }
}

Libreria/Views/Home/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Libreria La Jave</title>
    <link rel="stylesheet" href="~/css/HomePage.css">
</head>
<body>
    <div id="HomeWrapper">
        <header>
            <ul>
                <li>
                    <a>
                        Login
                    </a>
                </li>
                <li>
                    <a>
                        Otros
                    </a>
                </li>
                <li>
                    <a asp-controller="Autor" asp-action="Buscador">
                        Autores
                    </a>
                </li>
                <li>
                    <a asp-controller="Libros" asp-action="Index">
                        Libros
                    </a>
                </li>                
            </ul>
        </header>
        <section>
            <img src="~/images/HomePage.png" alt="">
            <label for="">"Leer es lo mejor...."</label>
        </section>
        <aside>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis, dolor vero eum fuga ea pariatur quas ut voluptates doloribus suscipit fugiat tempora? Distinctio, iure exercitationem rerum sunt ipsa illo totam?</p>
        </aside>
    </div>
</body>
</html>

Libreria/Views/Libros/Index.cshtml
@model Libreria.ViewModels.LibrosIndexViewModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/LibrosIndex.css">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <title>Libros</title>
</head>
<body>
    <div id="MainWrapper">
        <header>
            <a asp-controller="Home" asp-action="Index">Volver</a>
            <a>Nuevo libro</a>
        </header>
        <div id="WrapperLibros">
            @if(Model.HayLibros)
            {
                <table>
                    <thead>
                        <tr>
                            <th>Nombre Libro</th>
                            <th>Genero</th>
                            <th>Cantidad Páginas</th>
                            <th>Editar</th>
                            <th>Eliminar</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var libro in Model.Libros)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => libro.Nombre)</td>
                                <td>@Html.DisplayFor(modelItem => libro.Genero)</td>
                                <td>@Html.DisplayFor(modelItem => libro.CantidadPaginas)</td>
                                <td>
                                    <a><i class="far fa-edit"></i></a>#
                                </td>
                                <td><i class="far fa-edit"></i></td>
                            </tr>    
                        }
                    </tbody>
                </table>
            }
            else
            {
                <label for="">No hay libros en el sistema</label>
            }
        </div>
    </div>
</body>
</html>

Libreria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Libreria</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Libreria</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Libreria - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>